### ISSUE TITLE
Aura Missing Trigger

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/WeakAuras2-TBC-2.4.3#11] opened 2023-03-12 05:19 UTC
## Describe the bug
The Trigger -> Aura -> Show if Missing trigger doesn't check for the aura on initialization is seems.
I have this one set to only show in Combat. Sometimes it'll check again shortly after I enter combat and vanish, other times it'll just stay put being active the whole time when it shouldn't be.

![image](https://user-images.githubusercontent.com/72258441/224525760-9ad555da-f11a-49b1-9fd1-43943317c041.png)

https://user-images.githubusercontent.com/72258441/224525887-d6437f59-bda9-487e-b1e8-3e2e4297e267.mp4

**Comment by RichSteini** [comment] 2023-03-12 12:17
With on initialization you mean,  after you close the weakauras option window or after you log in? I can't reproduce this, for me it seems to work normal.

**Comment by Foodlenz** [comment] 2023-03-12 18:45
I mean since I have that aura set to only **load in combat**. I figured it worked like the Actions tab where it'd fire a check OnLoad or whatever. 
Which if it did, it would see that Battle Shout was already applied, and so wouldn't trigger the weakaura to fire the reminder to apply battle shout on my screen.

But if it works correctly for you, maybe it's another addon causing issues. I'll try it again when i get home tonight and check if that's the case.

**Comment by RichSteini** [comment] 2023-03-12 21:54
I tested everything through and it is working as expected for me. If i am out of combat then it does not show at all, does not matter if applied or not. If i enter combat and have it already applied then it does not show up and if i enter combat and i do not have it applied then it shows up instantly, and when i apply it while combat then it vanishes. Maybe try with other addons disabled then.

**Comment by RichSteini** [comment] 2023-03-13 11:52
Someone reported the same problem and figured out that it is caused by SpeedrunSplits https://github.com/RichSteini/WeakAuras2-TBC-2.4.3/issues/13. Are you using that too?

**Comment by Foodlenz** [comment] 2023-03-13 21:12
I was, yeah. Didn't get a chance to test addon conflicts last night, but probably that.

**Comment by RichSteini** [comment] 2023-03-13 21:52
Yes, we fixed SpeedrunSplits so it does not break WeakAuras anymore. Macumba will update the addon in the next few days. Closing this as it seems to be solved.

**Closed as completed** 2023-03-13 21:52 UTC
Labels: bug
